import 'package:isar/isar.dart';

part 'itinerary.g.dart'; // This will be generated by isar_generator

@collection
class Itinerary {
  Id id = Isar.autoIncrement; // auto-increment primary key
  late String title;
  late String content;
  late DateTime createdAt;
}
